services:
  - type: web
    name: agent-room-server
    runtime: node
    repo: https://github.com/yunusovabdullox36-hash/test
    branch: room-server
    buildCommand: npm install
    startCommand: node index.js
    plan: starter
    region: frankfurt
    healthCheckPath: /api/stats
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
